Organize the presentations page, add content and update links
eclipse/omr.website pull request #14
Opened 2017-08-11 19:56 UTC by dorrab

I have changed to division from recent/previous presentations to case studies/deep dives.
I think this is a better way to present the content.
I have added 2 recents talks by @mstoodle and @Leonardo2718
I have updated the broken links

2017-08-15 13:51 UTC, mstoodle requested changes
Thanks for making this update, Dorra! Just a couple small nits to fix.

2017-08-15 13:51 UTC, mstoodle commented on resources/presentations.md
> +- [*How does Eclipse OMR compare to LLVM*](http://www.ustream.tv/recorded/105013815) Mark Stoodley, June, 2017.
Technically, the title was "Eclipse OMR: How does all this compare to LLVM?"

2017-08-15 13:51 UTC, mstoodle commented on resources/presentations.md
> +- [*Eclipse OMR Update Tech Talk*](http://www.ustream.tv/recorded/98846650) Mark Stoodley, developerWorks Open, January 2017.
I know the talk didn't have a subtitle, but let's put one here to give people an idea what's in the presentation...Something like: "Eclipse OMR Update: compiler component, JitBuilder and projects that use them" ?

2017-08-15 13:51 UTC, mstoodle commented on resources/presentations.md
> +- [*Eclipse OMR Tech Talk*](https://developer.ibm.com/open/videos/eclipse-omr-tech-talk/) Mark Stoodley, developerWorks Open, July 2016.
Do you have a link to the CUSEC presentation that Robert and Kim and John and Shelley went to? I can provide it if not; we should really add it in here too.

2017-08-15 14:57 UTC, dorrab commented
Hello @mstoodle, I can't find the link. If you have it handy, please send it to me. Otherwise I can ask Shelley.

2017-08-15 15:40 UTC, mstoodle commented
The presentation is here, I believe: https://github.com/youngar/Base9/blob/master/CUSEC%202017%20-%20Buildering%20a%20JIT.pdf

2017-08-15 15:41 UTC, mstoodle commented on resources/presentations.md
> +- [*Eclipse OMR Tech Talk*](https://developer.ibm.com/open/videos/eclipse-omr-tech-talk/) Mark Stoodley, developerWorks Open, July 2016.
Actually, I think it was Andrew <blush>, since Base9 is under his github id...

2017-08-18 15:49 UTC, dorrab commented
Hello @mstoodle, addressed your comments above in the second commit. Please review. thank you

2017-08-23 21:42 UTC, youngar commented on resources/presentations.md
> +- [*Eclipse OMR Tech Talk*](https://developer.ibm.com/open/videos/eclipse-omr-tech-talk/) Mark Stoodley, developerWorks Open, July 2016.
Yeah, It was me and Kim who did the presentation

2017-08-24 18:38 UTC, mstoodle approved these changes

2017-08-24 18:40 UTC, mstoodle commented
Thanks @dorrab!

2017-08-24 18:40 UTC, merged