Improve the appeal for wanting to use Eclipse OMR
eclipse/omr.website pull request #7
Opened 2016-12-22 17:38 UTC by SueChaplain

Expanded the opening to this topic and included a new
section about why you would use it. Removed the component
list, which is repeated elsewhere.

Issue: #6
Signed-off-by: Sue Chaplain <sue_chaplain@uk.ibm.com>

2016-12-23 14:27 UTC, mstoodle requested changes

2016-12-23 14:27 UTC, mstoodle commented on starter/whatisomr.md
> +Despite decades of research and development in building languages and runtimes, almost none of the popular language runtimes share any common components. Many runtimes implement their own interface t
"cut right down on" sounds a bit odd in my head, though I think I recognize parts of this paragraph :) .

Maybe simplify to just "cut down on" ?

2016-12-23 14:27 UTC, mstoodle commented on starter/whatisomr.md
> +One of the most compelling reasons to use Eclipse OMR is the pedigree of the code. Many of the components have their roots in the **J9 virtual machine**; a high performance, scalable, enterprise clas
"Today, the J9" is missing something, I think. Maybe "Today, the J9 virtual machine consumes" ? Or just "Today, J9 consumes"?

2017-01-03 11:02 UTC, SueChaplain commented
I made the updates requested. Hopefully we can now merge.

2017-01-03 14:53 UTC, mstoodle approved these changes

2017-01-03 14:53 UTC, mstoodle commented
Thanks, Sue!

2017-01-03 14:53 UTC, merged